/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseWidgets: typeof import('./components/layout/pageLeft/base-widgets/index.vue')['default']
    ComDialog: typeof import('./components/work/comDialog/index.vue')['default']
    ContainerComponent: typeof import('./components/layout/pageLeft/container-component/index.vue')['default']
    copy: typeof import('./components/layout/pageLeft/custom-component copy/index.vue')['default']
    CustomComponent: typeof import('./components/layout/pageLeft/custom-component/index.vue')['default']
    DataSource: typeof import('./components/layout/pageLeft/data-source/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PageContainer: typeof import('./components/layout/pageContainer/index.vue')['default']
    PageHead: typeof import('./components/layout/pageHead/index.vue')['default']
    PageLeft: typeof import('./components/layout/pageLeft/index.vue')['default']
    PageRight: typeof import('./components/layout/pageRight/index.vue')['default']
    PageTree: typeof import('./components/layout/pageLeft/page-tree/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
